#!/usr/bin/env python3
"""Export insole boundary masks + centroids for frontend and embedded C."""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
INSOLES_BOUNDARY_SRC = REPO_ROOT / "tools" / "insoles-boundary" / "src"
PAYLOAD_PATH = REPO_ROOT / "tools" / "insoles-boundary" / "reports" / "render_payload.json"
FRONTEND_DATA = REPO_ROOT / "frontend" / "public" / "data"
BACKEND_DATA = REPO_ROOT / "backend_prod" / "data"
GENERATED_DIR = REPO_ROOT / "tools" / "win-datacap" / "generated"
OUTPUT_PATH = FRONTEND_DATA / "boundary_assets.json"
BACKEND_OUTPUT_PATH = BACKEND_DATA / "boundary_assets.json"
CENTROIDS_HEADER_PATH = GENERATED_DIR / "insole_sensor_centroids.h"


def _encode_rle(mask: np.ndarray) -> list[int]:
    """Run-length encode a boolean mask flattened row-major."""
    flat = mask.astype(np.uint8).ravel()
    if flat.size == 0:
        return []
    runs: list[int] = []
    current = int(flat[0])
    count = 1
    for value in flat[1:]:
        value = int(value)
        if value == current:
            count += 1
        else:
            runs.append(count)
            current = value
            count = 1
    runs.append(count)
    return runs


def export_boundary_assets() -> dict:
    if str(INSOLES_BOUNDARY_SRC) not in sys.path:
        sys.path.insert(0, str(INSOLES_BOUNDARY_SRC))

    from insoles.render_payload import (  # noqa: WPS433
        load_render_payload,
        region_label_centroids,
    )

    # Access internal renderer prep via render_sensor_field module cache path.
    from insoles import render_payload as rp  # noqa: WPS433

    payload = load_render_payload(PAYLOAD_PATH)
    renderer = rp._prepare_renderer(payload)  # noqa: SLF001

    centroids = [
        {"fsrIndex": fsr_index, "cx": cx, "cy": cy}
        for fsr_index, cx, cy in region_label_centroids(payload)
    ]

    masks = []
    for fsr_index, mask in enumerate(renderer.sensor_masks):
        masks.append(
            {
                "fsrIndex": fsr_index,
                "width": renderer.width,
                "height": renderer.height,
                "rle": _encode_rle(mask),
                "startsWith": 0,
            }
        )

    return {
        "schema": "insoles.boundary_assets/v1",
        "sourcePayload": "render_payload.json",
        "canvas": {
            "width": renderer.width,
            "height": renderer.height,
        },
        "centroids": centroids,
        "masks": masks,
    }


def _centroids_checksum(centroids: list[dict[str, float | int]]) -> str:
    """Stable checksum for centroid tables (detect drift vs JSON export)."""
    payload = json.dumps(centroids, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _format_c_float(value: float) -> str:
    text = f"{float(value):.8f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return f"{text}f"


def _render_centroid_table(name: str, entries: list[tuple[float, float]]) -> str:
    lines = [f"static const insole_centroid_t {name}[INSOLE_SENSOR_COUNT] = {{"]
    for index, (x, y) in enumerate(entries):
        comma = "," if index < len(entries) - 1 else ""
        lines.append(
            f"    {{ {_format_c_float(x)}, {_format_c_float(y)} }}{comma}"
        )
    lines.append("};")
    return "\n".join(lines)


def export_sensor_centroids_header(assets: dict) -> str:
    """Generate C header with pre-mirrored left-foot plot coordinates."""
    canvas = assets["canvas"]
    width = int(canvas["width"])
    height = int(canvas["height"])
    centroids = sorted(assets["centroids"], key=lambda item: int(item["fsrIndex"]))

    right_entries = [(float(item["cx"]), float(item["cy"])) for item in centroids]
    left_entries = [
        (float(width - 1) - float(item["cx"]), float(item["cy"])) for item in centroids
    ]
    checksum = _centroids_checksum(list(assets["centroids"]))
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    return f"""\
/* Auto-generated by tools/scripts/export_boundary_assets.py — do not edit. */
#ifndef INSOLE_SENSOR_CENTROIDS_H
#define INSOLE_SENSOR_CENTROIDS_H

#include <stdint.h>

#define INSOLE_CANVAS_WIDTH   {width}
#define INSOLE_CANVAS_HEIGHT  {height}
#define INSOLE_SENSOR_COUNT   16

/* sourcePayload: {assets["sourcePayload"]} */
/* generatedAtUtc: {generated_at} */
/* centroidsChecksum: {checksum} */

typedef struct {{
    float x;
    float y;
}} insole_centroid_t;

/* Plot coordinates: top-left origin, x = column, y = row (ADR-0004). */
{_render_centroid_table("INSOLE_CENTROID_RIGHT", right_entries)}

/* Left foot: x pre-mirrored as (canvas_width - 1 - cx). */
{_render_centroid_table("INSOLE_CENTROID_LEFT", left_entries)}

#endif /* INSOLE_SENSOR_CENTROIDS_H */
"""


def write_sensor_centroids_header(assets: dict) -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    content = export_sensor_centroids_header(assets)
    CENTROIDS_HEADER_PATH.write_text(content, encoding="utf-8", newline="\n")
    return CENTROIDS_HEADER_PATH


def main() -> None:
    FRONTEND_DATA.mkdir(parents=True, exist_ok=True)
    BACKEND_DATA.mkdir(parents=True, exist_ok=True)
    assets = export_boundary_assets()
    for output_path in (OUTPUT_PATH, BACKEND_OUTPUT_PATH):
        with output_path.open("w", encoding="utf-8") as handle:
            json.dump(assets, handle, ensure_ascii=False, separators=(",", ":"))
            handle.write("\n")
        print(f"Wrote {output_path}")

    payload_dest = FRONTEND_DATA / "render_payload.json"
    shutil.copy2(PAYLOAD_PATH, payload_dest)
    print(f"Copied {payload_dest}")

    header_path = write_sensor_centroids_header(assets)
    print(f"Wrote {header_path}")


if __name__ == "__main__":
    main()
